org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.88

mod_id=brainmeth_core
mod_name=Brainmeth Core
mod_license=All Rights Reserved
mod_version=0.1.0
mod_group_id=dev.cybersans.brainmeth
