name = "Brainmeth"
author = "Cyber"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd81ef51daf3ef9e8f1c4b7031c68090157dc190666e518d4b004f60ffbc6c9"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
