name = "Brainmeth"
author = "Cyber"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a097f63c0943c0515b1df3a2ea5f174c687d4e839f978b5b1febef48c7992fe"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
