name = "Brainmeth"
author = "Cyber"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7d6fe199ba58331d089529e08175d20951a40a9b32c72bc9743ac504a15746a"

[versions]
minecraft = "26.2"
neoforge = "26.2.0.88"
